name: K6 Performance Test

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 12 * * 1'  # Runs every Monday at 12:00 UTC

jobs:
  k6-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install K6
        run: |
          sudo apt update
          sudo apt install -y k6

      - name: Run K6 Test
        run: k6 run test.js