name: K6 Performance Test

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 12 * * 1'  # Runs every Monday at 12:00 UTC

jobs:
  k6-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install K6 using Snap
        run: |
          sudo apt update
          sudo snap install k6

      - name: Run K6 Test
        run: k6 run loadTest/test.js
      
      - name: Upload K6 Report
        uses: actions/upload-artifact@v4
        with:
          name: k6-report
          path: |
            playwright-report/
          retention-days: 10