name: K6 Performance Test (TypeScript)

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 12 * * 1-3'  # Runs every Monday-wed at 12:00 UTC

jobs:
  k6-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo snap install k6
          npm install --save-dev typescript @types/k6 esbuild

      - name: Transpile TypeScript
        run: npx esbuild loadTest/k6ts-test.ts --bundle --outfile=loadTest/test.js

      - name: Run K6 Test
        run: k6 run loadTest/k6ts-test.js
      
      - name: Upload K6 Report
        uses: actions/upload-artifact@v4
        with:
          name: k6-tsreport